export const userData = {
  delivery: [
    {
      id: 1,
      name: "John Doe",
      email: "john.doe@example.com",
      location: "New York, NY",
      active: true,
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane.smith@example.com",
      location: "Los Angeles, CA",
      active: true,
    },
    {
      id: 3,
      name: "Robert Johnson",
      email: "robert.johnson@example.com",
      location: "Chicago, IL",
      active: true,
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      location: "Houston, TX",
      active: true,
    },
    {
      id: 5,
      name: "Michael Brown",
      email: "michael.brown@example.com",
      location: "Miami, FL",
      active: false,
    },
    {
      id: 6,
      name: "Mary Wilson",
      email: "mary.wilson@example.com",
      location: "Seattle, WA",
      active: true,
    },
    {
      id: 7,
      name: "David Martinez",
      email: "david.martinez@example.com",
      location: "Dallas, TX",
      active: false,
    },
    {
      id: 8,
      name: "Sarah Garcia",
      email: "sarah.garcia@example.com",
      location: "San Francisco, CA",
      active: true,
    },
    {
      id: 9,
      name: "James Moore",
      email: "james.moore@example.com",
      location: "Austin, TX",
      active: true,
    },
    {
      id: 10,
      name: "Linda Taylor",
      email: "linda.taylor@example.com",
      location: "Orlando, FL",
      active: true,
    },
    {
      id: 11,
      name: "William Anderson",
      email: "william.anderson@example.com",
      location: "Boston, MA",
      active: true,
    },
    {
      id: 12,
      name: "Joseph Thomas",
      email: "joseph.thomas@example.com",
      location: "Phoenix, AZ",
      active: true,
    },
    {
      id: 13,
      name: "Patricia Jackson",
      email: "patricia.jackson@example.com",
      location: "San Diego, CA",
      active: true,
    },
    {
      id: 14,
      name: "Charles White",
      email: "charles.white@example.com",
      location: "Las Vegas, NV",
      active: false,
    },
    {
      id: 15,
      name: "Jessica Harris",
      email: "jessica.harris@example.com",
      location: "Atlanta, GA",
      active: true,
    },
    {
      id: 16,
      name: "Thomas Martin",
      email: "thomas.martin@example.com",
      location: "New Orleans, LA",
      active: false,
    },
    {
      id: 17,
      name: "Nancy Thompson",
      email: "nancy.thompson@example.com",
      location: "Detroit, MI",
      active: true,
    },
    {
      id: 18,
      name: "Steven Garcia",
      email: "steven.garcia@example.com",
      location: "Washington, DC",
      active: true,
    },
    {
      id: 19,
      name: "Betty Clark",
      email: "betty.clark@example.com",
      location: "Chicago, IL",
      active: true,
    },
    {
      id: 20,
      name: "Daniel Lewis",
      email: "daniel.lewis@example.com",
      location: "Minneapolis, MN",
      active: true,
    },
    {
      id: 21,
      name: "Martha Lee",
      email: "martha.lee@example.com",
      location: "Philadelphia, PA",
      active: true,
    },
    {
      id: 22,
      name: "Henry Walker",
      email: "henry.walker@example.com",
      location: "Portland, OR",
      active: false,
    },
    {
      id: 23,
      name: "Margaret Allen",
      email: "margaret.allen@example.com",
      location: "Miami, FL",
      active: true,
    },
    {
      id: 24,
      name: "Christopher Young",
      email: "christopher.young@example.com",
      location: "Dallas, TX",
      active: true,
    },
    {
      id: 25,
      name: "Samantha King",
      email: "samantha.king@example.com",
      location: "Denver, CO",
      active: true,
    },
    {
      id: 26,
      name: "Jack Scott",
      email: "jack.scott@example.com",
      location: "Los Angeles, CA",
      active: false,
    },
    {
      id: 27,
      name: "Dorothy Adams",
      email: "dorothy.adams@example.com",
      location: "Houston, TX",
      active: true,
    },
    {
      id: 28,
      name: "Matthew Nelson",
      email: "matthew.nelson@example.com",
      location: "Phoenix, AZ",
      active: true,
    },
    {
      id: 29,
      name: "Kimberly Carter",
      email: "kimberly.carter@example.com",
      location: "Boston, MA",
      active: false,
    },
    {
      id: 30,
      name: "George Mitchell",
      email: "george.mitchell@example.com",
      location: "Chicago, IL",
      active: true,
    },
  ],
};
