export const userData = {
  customers: [
    {
      id: "U001",
      name: "Alice Johnson",
      email: "alice@example.com",
      status: "active",
    },
    {
      id: "U002",
      name: "Bob Smith",
      email: "bob@example.com",
      status: "active",
    },
    {
      id: "U003",
      name: "Charlie Lee",
      email: "charlie@example.com",
      status: "disabled",
    },
    {
      id: "U004",
      name: "David Kim",
      email: "david@example.com",
      status: "active",
    },
    {
      id: "U005",
      name: "Ella Martinez",
      email: "ella@example.com",
      status: "warned",
    },
    {
      id: "U006",
      name: "Fiona Brown",
      email: "fiona@example.com",
      status: "active",
    },
    {
      id: "U007",
      name: "George Wilson",
      email: "george@example.com",
      status: "disabled",
    },
    {
      id: "U008",
      name: "Hannah Clark",
      email: "hannah@example.com",
      status: "active",
    },
    {
      id: "U009",
      name: "Ian Scott",
      email: "ian@example.com",
      status: "active",
    },
    {
      id: "U010",
      name: "Jenny Adams",
      email: "jenny@example.com",
      status: "warned",
    },
    {
      id: "U011",
      name: "Kevin White",
      email: "kevin@example.com",
      status: "active",
    },
    {
      id: "U012",
      name: "Lily King",
      email: "lily@example.com",
      status: "active",
    },
    {
      id: "U013",
      name: "Matt Green",
      email: "matt@example.com",
      status: "disabled",
    },
    {
      id: "U014",
      name: "Nina Hall",
      email: "nina@example.com",
      status: "active",
    },
    {
      id: "U015",
      name: "Oliver Young",
      email: "oliver@example.com",
      status: "warned",
    },
    {
      id: "U016",
      name: "Paula Baker",
      email: "paula@example.com",
      status: "active",
    },
    {
      id: "U017",
      name: "Quentin Reed",
      email: "quentin@example.com",
      status: "active",
    },
    {
      id: "U018",
      name: "Rachel Morris",
      email: "rachel@example.com",
      status: "disabled",
    },
    {
      id: "U019",
      name: "Sam Cooper",
      email: "sam@example.com",
      status: "active",
    },
    {
      id: "U020",
      name: "Tina Cox",
      email: "tina@example.com",
      status: "active",
    },
    {
      id: "U021",
      name: "Uma Bell",
      email: "uma@example.com",
      status: "warned",
    },
    {
      id: "U022",
      name: "Victor Turner",
      email: "victor@example.com",
      status: "active",
    },
    {
      id: "U023",
      name: "Wendy Parker",
      email: "wendy@example.com",
      status: "disabled",
    },
    {
      id: "U024",
      name: "Xander Evans",
      email: "xander@example.com",
      status: "active",
    },
    {
      id: "U025",
      name: "Yasmin Sanders",
      email: "yasmin@example.com",
      status: "warned",
    },
    {
      id: "U026",
      name: "Zachary Brooks",
      email: "zachary@example.com",
      status: "active",
    },
    {
      id: "U027",
      name: "Abigail James",
      email: "abigail@example.com",
      status: "active",
    },
    {
      id: "U028",
      name: "Brian Foster",
      email: "brian@example.com",
      status: "disabled",
    },
    {
      id: "U029",
      name: "Cynthia Ross",
      email: "cynthia@example.com",
      status: "active",
    },
    {
      id: "U030",
      name: "Derek Howard",
      email: "derek@example.com",
      status: "active",
    },
  ],
  restaurants: [
    {
      id: 1,
      name: "The Gourmet Kitchen",
      email: "gourmetkitchen@example.com",
      location: "New York, NY",
      rating: 4.5,
      orders: 230,
    },
    {
      id: 2,
      name: "Taco Haven",
      email: "tacohaven@example.com",
      location: "Los Angeles, CA",
      rating: 4.0,
      orders: 120,
    },
    {
      id: 3,
      name: "Sushi World",
      email: "sushiworld@example.com",
      location: "San Francisco, CA",
      rating: 4.8,
      orders: 500,
    },
    {
      id: 4,
      name: "Pasta Paradise",
      email: "pastaparadise@example.com",
      location: "Chicago, IL",
      rating: 4.3,
      orders: 350,
    },
    {
      id: 5,
      name: "Burger Barn",
      email: "burgerbarn@example.com",
      location: "Miami, FL",
      rating: 4.2,
      orders: 420,
    },
    {
      id: 6,
      name: "Café Delight",
      email: "cafedelight@example.com",
      location: "Seattle, WA",
      rating: 4.6,
      orders: 180,
    },
    {
      id: 7,
      name: "Vegan Vibes",
      email: "veganvibes@example.com",
      location: "Austin, TX",
      rating: 4.7,
      orders: 150,
    },
    {
      id: 8,
      name: "Spicy Street",
      email: "spicystreet@example.com",
      location: "Houston, TX",
      rating: 4.4,
      orders: 300,
    },
    {
      id: 9,
      name: "Pizzeria Bella",
      email: "pizzeriabella@example.com",
      location: "Las Vegas, NV",
      rating: 4.9,
      orders: 600,
    },
    {
      id: 10,
      name: "Seafood Shack",
      email: "seafoodshack@example.com",
      location: "Boston, MA",
      rating: 4.1,
      orders: 250,
    },
    {
      id: 11,
      name: "Delicious Diner",
      email: "deliciousdiner@example.com",
      location: "Dallas, TX",
      rating: 4.2,
      orders: 300,
    },
    {
      id: 12,
      name: "Brew Bistro",
      email: "brewbistro@example.com",
      location: "Denver, CO",
      rating: 4.3,
      orders: 175,
    },
    {
      id: 13,
      name: "Grill House",
      email: "grillhouse@example.com",
      location: "Portland, OR",
      rating: 4.4,
      orders: 250,
    },
    {
      id: 14,
      name: "Healthy Eats",
      email: "healthyeats@example.com",
      location: "San Diego, CA",
      rating: 4.5,
      orders: 400,
    },
    {
      id: 15,
      name: "Pizza Place",
      email: "pizzaplace@example.com",
      location: "Orlando, FL",
      rating: 4.1,
      orders: 180,
    },
    {
      id: 16,
      name: "Burger King",
      email: "burgerking@example.com",
      location: "Phoenix, AZ",
      rating: 3.9,
      orders: 500,
    },
    {
      id: 17,
      name: "Sushi Express",
      email: "sushiexpress@example.com",
      location: "Los Angeles, CA",
      rating: 4.6,
      orders: 300,
    },
    {
      id: 18,
      name: "BBQ Bounty",
      email: "bbqbounty@example.com",
      location: "Charlotte, NC",
      rating: 4.3,
      orders: 250,
    },
    {
      id: 19,
      name: "Café Central",
      email: "cafecentral@example.com",
      location: "Washington, DC",
      rating: 4.2,
      orders: 150,
    },
    {
      id: 20,
      name: "Ramen Spot",
      email: "ramenspot@example.com",
      location: "Minneapolis, MN",
      rating: 4.5,
      orders: 320,
    },
    {
      id: 21,
      name: "Smoothie Paradise",
      email: "smoothieparadise@example.com",
      location: "Austin, TX",
      rating: 4.8,
      orders: 100,
    },
    {
      id: 22,
      name: "Burrito Bros",
      email: "burritobros@example.com",
      location: "Phoenix, AZ",
      rating: 4.4,
      orders: 190,
    },
    {
      id: 23,
      name: "The Pancake House",
      email: "pancakehouse@example.com",
      location: "Chicago, IL",
      rating: 4.0,
      orders: 130,
    },
    {
      id: 24,
      name: "Steak Street",
      email: "steakstreet@example.com",
      location: "Nashville, TN",
      rating: 4.7,
      orders: 290,
    },
    {
      id: 25,
      name: "Falafel Fusion",
      email: "falavelfusion@example.com",
      location: "New York, NY",
      rating: 4.6,
      orders: 250,
    },
    {
      id: 26,
      name: "The Fish Fry",
      email: "fishfry@example.com",
      location: "New Orleans, LA",
      rating: 4.2,
      orders: 180,
    },
    {
      id: 27,
      name: "Pasta Piazza",
      email: "pastapiazza@example.com",
      location: "Los Angeles, CA",
      rating: 4.5,
      orders: 340,
    },
    {
      id: 28,
      name: "Baking Bliss",
      email: "bakingbliss@example.com",
      location: "Portland, OR",
      rating: 4.3,
      orders: 120,
    },
    {
      id: 29,
      name: "Tandoori Treats",
      email: "tandooritreats@example.com",
      location: "Dallas, TX",
      rating: 4.7,
      orders: 500,
    },
    {
      id: 30,
      name: "Fresh Fusion",
      email: "freshfusion@example.com",
      location: "Atlanta, GA",
      rating: 4.8,
      orders: 600,
    },
  ],
  delivery: [
    {
      id: 1,
      name: "John Doe",
      email: "john.doe@example.com",
      location: "New York, NY",
      active: true,
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane.smith@example.com",
      location: "Los Angeles, CA",
      active: true,
    },
    {
      id: 3,
      name: "Robert Johnson",
      email: "robert.johnson@example.com",
      location: "Chicago, IL",
      active: true,
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      location: "Houston, TX",
      active: true,
    },
    {
      id: 5,
      name: "Michael Brown",
      email: "michael.brown@example.com",
      location: "Miami, FL",
      active: false,
    },
    {
      id: 6,
      name: "Mary Wilson",
      email: "mary.wilson@example.com",
      location: "Seattle, WA",
      active: true,
    },
    {
      id: 7,
      name: "David Martinez",
      email: "david.martinez@example.com",
      location: "Dallas, TX",
      active: false,
    },
    {
      id: 8,
      name: "Sarah Garcia",
      email: "sarah.garcia@example.com",
      location: "San Francisco, CA",
      active: true,
    },
    {
      id: 9,
      name: "James Moore",
      email: "james.moore@example.com",
      location: "Austin, TX",
      active: true,
    },
    {
      id: 10,
      name: "Linda Taylor",
      email: "linda.taylor@example.com",
      location: "Orlando, FL",
      active: true,
    },
    {
      id: 11,
      name: "William Anderson",
      email: "william.anderson@example.com",
      location: "Boston, MA",
      active: true,
    },
    {
      id: 12,
      name: "Joseph Thomas",
      email: "joseph.thomas@example.com",
      location: "Phoenix, AZ",
      active: true,
    },
    {
      id: 13,
      name: "Patricia Jackson",
      email: "patricia.jackson@example.com",
      location: "San Diego, CA",
      active: true,
    },
    {
      id: 14,
      name: "Charles White",
      email: "charles.white@example.com",
      location: "Las Vegas, NV",
      active: false,
    },
    {
      id: 15,
      name: "Jessica Harris",
      email: "jessica.harris@example.com",
      location: "Atlanta, GA",
      active: true,
    },
    {
      id: 16,
      name: "Thomas Martin",
      email: "thomas.martin@example.com",
      location: "New Orleans, LA",
      active: false,
    },
    {
      id: 17,
      name: "Nancy Thompson",
      email: "nancy.thompson@example.com",
      location: "Detroit, MI",
      active: true,
    },
    {
      id: 18,
      name: "Steven Garcia",
      email: "steven.garcia@example.com",
      location: "Washington, DC",
      active: true,
    },
    {
      id: 19,
      name: "Betty Clark",
      email: "betty.clark@example.com",
      location: "Chicago, IL",
      active: true,
    },
    {
      id: 20,
      name: "Daniel Lewis",
      email: "daniel.lewis@example.com",
      location: "Minneapolis, MN",
      active: true,
    },
    {
      id: 21,
      name: "Martha Lee",
      email: "martha.lee@example.com",
      location: "Philadelphia, PA",
      active: true,
    },
    {
      id: 22,
      name: "Henry Walker",
      email: "henry.walker@example.com",
      location: "Portland, OR",
      active: false,
    },
    {
      id: 23,
      name: "Margaret Allen",
      email: "margaret.allen@example.com",
      location: "Miami, FL",
      active: true,
    },
    {
      id: 24,
      name: "Christopher Young",
      email: "christopher.young@example.com",
      location: "Dallas, TX",
      active: true,
    },
    {
      id: 25,
      name: "Samantha King",
      email: "samantha.king@example.com",
      location: "Denver, CO",
      active: true,
    },
    {
      id: 26,
      name: "Jack Scott",
      email: "jack.scott@example.com",
      location: "Los Angeles, CA",
      active: false,
    },
    {
      id: 27,
      name: "Dorothy Adams",
      email: "dorothy.adams@example.com",
      location: "Houston, TX",
      active: true,
    },
    {
      id: 28,
      name: "Matthew Nelson",
      email: "matthew.nelson@example.com",
      location: "Phoenix, AZ",
      active: true,
    },
    {
      id: 29,
      name: "Kimberly Carter",
      email: "kimberly.carter@example.com",
      location: "Boston, MA",
      active: false,
    },
    {
      id: 30,
      name: "George Mitchell",
      email: "george.mitchell@example.com",
      location: "Chicago, IL",
      active: true,
    },
  ],
  admin: [
    {
      id: "U001",
      name: "Alice Johnson",
      email: "alice@example.com",
      status: "active",
    },
    {
      id: "U002",
      name: "Bob Smith",
      email: "bob@example.com",
      status: "active",
    },
    {
      id: "U003",
      name: "Charlie Lee",
      email: "charlie@example.com",
      status: "disabled",
    },
    {
      id: "U004",
      name: "David Kim",
      email: "david@example.com",
      status: "active",
    },
    {
      id: "U005",
      name: "Ella Martinez",
      email: "ella@example.com",
      status: "warned",
    },
    {
      id: "U006",
      name: "Fiona Brown",
      email: "fiona@example.com",
      status: "active",
    },
    {
      id: "U007",
      name: "George Wilson",
      email: "george@example.com",
      status: "disabled",
    },
    {
      id: "U008",
      name: "Hannah Clark",
      email: "hannah@example.com",
      status: "active",
    },
    {
      id: "U009",
      name: "Ian Scott",
      email: "ian@example.com",
      status: "active",
    },
    {
      id: "U010",
      name: "Jenny Adams",
      email: "jenny@example.com",
      status: "warned",
    },
    {
      id: "U011",
      name: "Kevin White",
      email: "kevin@example.com",
      status: "active",
    },
    {
      id: "U012",
      name: "Lily King",
      email: "lily@example.com",
      status: "active",
    },
    {
      id: "U013",
      name: "Matt Green",
      email: "matt@example.com",
      status: "disabled",
    },
    {
      id: "U014",
      name: "Nina Hall",
      email: "nina@example.com",
      status: "active",
    },
    {
      id: "U015",
      name: "Oliver Young",
      email: "oliver@example.com",
      status: "warned",
    },
    {
      id: "U016",
      name: "Paula Baker",
      email: "paula@example.com",
      status: "active",
    },
    {
      id: "U017",
      name: "Quentin Reed",
      email: "quentin@example.com",
      status: "active",
    },
    {
      id: "U018",
      name: "Rachel Morris",
      email: "rachel@example.com",
      status: "disabled",
    },
    {
      id: "U019",
      name: "Sam Cooper",
      email: "sam@example.com",
      status: "active",
    },
    {
      id: "U020",
      name: "Tina Cox",
      email: "tina@example.com",
      status: "active",
    },
    {
      id: "U021",
      name: "Uma Bell",
      email: "uma@example.com",
      status: "warned",
    },
    {
      id: "U022",
      name: "Victor Turner",
      email: "victor@example.com",
      status: "active",
    },
    {
      id: "U023",
      name: "Wendy Parker",
      email: "wendy@example.com",
      status: "disabled",
    },
    {
      id: "U024",
      name: "Xander Evans",
      email: "xander@example.com",
      status: "active",
    },
    {
      id: "U025",
      name: "Yasmin Sanders",
      email: "yasmin@example.com",
      status: "warned",
    },
    {
      id: "U026",
      name: "Zachary Brooks",
      email: "zachary@example.com",
      status: "active",
    },
    {
      id: "U027",
      name: "Abigail James",
      email: "abigail@example.com",
      status: "active",
    },
    {
      id: "U028",
      name: "Brian Foster",
      email: "brian@example.com",
      status: "disabled",
    },
    {
      id: "U029",
      name: "Cynthia Ross",
      email: "cynthia@example.com",
      status: "active",
    },
    {
      id: "U030",
      name: "Derek Howard",
      email: "derek@example.com",
      status: "active",
    },
  ],
};
